Repository RonaldoSwift/MeditationAppUI, pull requests merged in 2024-02, with the labels that each got.

#4 Add SilentMoonView
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI/App/MeditationAppUIApp.swift
  MeditationAppUI/Assets.xcassets/Colors/ColorButton.colorset/Contents.json
  MeditationAppUI/Assets.xcassets/Colors/ColorLetras.colorset/Contents.json
  MeditationAppUI/Assets.xcassets/Colors/Contents.json
  MeditationAppUI/Assets.xcassets/ImagenesP/Contents.json
  MeditationAppUI/Assets.xcassets/ImagenesP/FondoSilentMoon.imageset/Contents.json
  MeditationAppUI/Assets.xcassets/ImagenesP/FondoSilentMoon.imageset/Fondo.svg
  MeditationAppUI/Assets.xcassets/ImagenesP/ImagenInici.imageset/Contents.json
  MeditationAppUI/Assets.xcassets/ImagenesP/ImagenInici.imageset/Group.svg
  MeditationAppUI/Assets.xcassets/ImagenesP/Logo.imageset/Contents.json
  MeditationAppUI/Assets.xcassets/ImagenesP/Logo.imageset/logo.svg
  MeditationAppUI/Core/ButtonStyle/GeneralButtonComponent.swift
  MeditationAppUI/Info.plist
  MeditationAppUI/Presentation/SignUpAndSignView.swift
  MeditationAppUI/Presentation/SilentMoon/SilentMoonView.swift
  MeditationAppUI/Resources/Fonts/HelveticaNeueBlackCondensed.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueBoldCondensed.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-Black.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-BlackItalic.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-Bold.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-BoldItalic.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-Heavy.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-HeavyItalic.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-Italic.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-Light.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-LightItalic.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-Medium.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-MediumItalic.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-Roman.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-Thin.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-ThinItalic.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-UltraLight.ttf
  MeditationAppUI/Resources/Fonts/HelveticaNeueCyr-UltraLightItalic.ttf
Labels: documentation

#6 Add SignInView, Update SilentmoonView
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI.xcodeproj/xcuserdata/ronaldoandre.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  MeditationAppUI/Assets.xcassets/Colors/ColorButtonFacebook.colorset/Contents.json
  MeditationAppUI/Assets.xcassets/Colors/ColorButtonGoogle.colorset/Contents.json
  MeditationAppUI/Assets.xcassets/Colors/ColorSignInTextField.colorset/Contents.json
  MeditationAppUI/Assets.xcassets/ImagenesP/LogoFacebook.imageset/Contents.json
  MeditationAppUI/Assets.xcassets/ImagenesP/LogoFacebook.imageset/LogoFacebook.svg
  MeditationAppUI/Assets.xcassets/ImagenesP/LogoGoogle.imageset/Contents.json
  MeditationAppUI/Assets.xcassets/ImagenesP/LogoGoogle.imageset/LogoGoogle.svg
  MeditationAppUI/Assets.xcassets/ImagenesP/SignInFondo.imageset/Contents.json
  MeditationAppUI/Assets.xcassets/ImagenesP/SignInFondo.imageset/SignInFondo.svg
  MeditationAppUI/Core/ButtonStyle/GeneralButtonComponent.swift
  MeditationAppUI/Presentation/SignIn/SignInView.swift
  MeditationAppUI/Presentation/SilentMoon/SilentMoonView.swift
Labels: enhancement

#11 Add Swiftgen - authenticationblack
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI.xcodeproj/xcuserdata/ronaldoandre.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  MeditationAppUI/Assets.xcassets/AccentColor.colorset/Contents.json
  MeditationAppUI/Assets.xcassets/ImagenesP/Contents.json
  MeditationAppUI/Generated/Fonts.swift
  MeditationAppUI/Generated/JSON.swift
  MeditationAppUI/Generated/Strings.swift
  MeditationAppUI/Navigation/Root/RootViews/Authentication/AuthenticationRootView.swift
  MeditationAppUI/Navigation/Splash/SplashView.swift
  MeditationAppUI/Presentation/SignIn/SignInView.swift
  MeditationAppUI/Presentation/SilentMoon/SilentMoonView.swift
  MeditationAppUI/Resources/Assets/Colores.xcassets/ColorButton.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/ColorButtonFacebook.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/ColorButtonGoogle.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/ColorCheck.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/ColorLetras.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/ColorSignInTextField.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/AppIcon.appiconset/AppIcon.png
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/AppIcon.appiconset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/CheckSinUp.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/CheckSinUp.imageset/checkSignUp.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/FondoSilentMoon.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/FondoSilentMoon.imageset/Fondo.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/ImagenInici.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/ImagenInici.imageset/Group.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Logo.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Logo.imageset/logo.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/LogoFacebook.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/LogoFacebook.imageset/LogoFacebook.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/LogoGoogle.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/LogoGoogle.imageset/LogoGoogle.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/SignInFondo.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/SignInFondo.imageset/SignInFondo.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/TabSignUp.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/TabSignUp.imageset/eyebrow.svg
  MeditationAppUI/Resources/en.lproj/Localizable.strings
  MeditationAppUI/Resources/es-419.lproj/Localizable.strings
  swiftgen.yml
Labels: documentation

#14 Add welcomeview
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI/Core/ButtonStyle/GeneralButtonComponent.swift
  MeditationAppUI/Presentation/Welcome/WelcomeView.swift
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackground1.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackground2.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentLabel1.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentLabel2.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/PrimaryBackground.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/PrimaryLabel.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/SecondaryBackground.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/SecondaryLabel.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Welcome.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Welcome.imageset/Welcome.png
Labels: Ui
