Repository RonaldoSwift/MeditationAppUI, pull requests merged in 2024-03, with the labels that each got.

#24 Add HomeView, PrincipalView
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI/Generated/Fonts.swift
  MeditationAppUI/Generated/Strings.swift
  MeditationAppUI/Navigation/Home/HomeView.swift
  MeditationAppUI/Presentation/Home/HomeView.swift
  MeditationAppUI/Presentation/Principal/PrincipalView.swift
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackgroundCard.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/BasicsCourse.imageset/BasicsImage.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/BasicsCourse.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/DailyCard.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/DailyCard.imageset/DailycARD.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/HouseIcon.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/HouseIcon.imageset/HouseIcon.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/LunaIcon.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/LunaIcon.imageset/LunaIcon.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/MeditateIcon.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/MeditateIcon.imageset/MeditateIcon.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/MusicIcon.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/MusicIcon.imageset/MusicIcon.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PersonIcon.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PersonIcon.imageset/PersonIcon.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PlayImage.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PlayImage.imageset/PlayImage.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/RelaxionImage.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/RelaxionImage.imageset/RelaxionImagen.svg
Labels: Ui

#27 Update github actions
  .github/workflows/swift.yml
  .swiftformat
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI.xcworkspace/contents.xcworkspacedata
  MeditationAppUI.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MeditationAppUI/Presentation/Welcome/WelcomeView.swift
  Podfile
  Podfile.lock
  README.md
Labels: Do Not Merge

#34 New play music
  .github/workflows/swift.yml
  .swiftformat
  .swiftlint.yml
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI/App/AppDelegate.swift
  MeditationAppUI/App/MeditationAppUIApp.swift
  MeditationAppUI/Data/DataSource/FireBaseAuthDataSource.swift
  MeditationAppUI/Domain/Modelo/Song.swift
  MeditationAppUI/Presentation/PlayMusic/DiscView.swift
  MeditationAppUI/Presentation/PlayMusic/MusicMediaPlayer.swift
  MeditationAppUI/Presentation/PlayMusic/PlayMusicView.swift
  MeditationAppUI/Presentation/PlayMusic/PlayerSliderViewModel.swift
  MeditationAppUI/Presentation/SignIn/SignInView.swift
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackground3.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/Tint.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/Tint2.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/FastForward.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/FastForward.imageset/FastForward.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/FastRewind.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/FastRewind.imageset/FastRewind.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Pause.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Pause.imageset/Pause.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PlayMusicBackground.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PlayMusicBackground.imageset/PlayMusicBackground.png
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Vinille.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Vinille.imageset/vinille.png
  Podfile
  README.md
Labels: enhancement, Ui

#38 Added local notifications with imagenes, icons, actions, icons
  ImagesForBundle/ronaldo.jpeg
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI/App/AppDelegate+Extensions.swift
  MeditationAppUI/App/AppDelegate.swift
  MeditationAppUI/Notifications/NotificationAttachment+Extensions.swift
  MeditationAppUI/Notifications/NotificationManager.swift
  MeditationAppUI/Notifications/TriggerType.swift
  MockApns/test.apn
  Podfile.lock
Labels: enhancement, Ui

#39 Add MeditateView and Update HomeView
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI.xcodeproj/project.pbxproj.orig
  MeditationAppUI/Presentation/Home/HomeView.swift
  MeditationAppUI/Presentation/Meditation/MeditationView.swift
  MeditationAppUI/Presentation/Principal/PrincipalView.swift
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackgroundCard2.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccenteBackgroundCard3.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccenteBackgroundCard4.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Alls.imageset/All.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Alls.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Ambiente.imageset/Ambiente.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Ambiente.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Anioxus.imageset/Anxious.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Anioxus.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/AnxietRelease.imageset/AnxietRelease.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/AnxietRelease.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Dais.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Dais.imageset/Dais.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/DaysOfCalm.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/DaysOfCalm.imageset/DaysOfCalm.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Focus.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Focus.imageset/Focus.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/FondDailyCalm.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/FondDailyCalm.imageset/FondDailyCalm.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Happiness.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Happiness.imageset/Happiness.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Heart.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Heart.imageset/heart.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PlayBlack.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PlayBlack.imageset/PlayBlack.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Sleep.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Sleep.imageset/sleep.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/kids.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/kids.imageset/kids.svg
Labels: Ui

#42 Add HappyMorningView
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI/Presentation/HappyMorning/HappyMorningView.swift
  MeditationAppUI/Presentation/Principal/PrincipalView.swift
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Auricular.imageset/Auricular.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Auricular.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Back.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Back.imageset/back.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Dowload.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Dowload.imageset/Descargar.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/HappyMorning.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/HappyMorning.imageset/HappyGru.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/HeartEncendido.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/HeartEncendido.imageset/Heart.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Like.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Like.imageset/like.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PlayNormal.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PlayNormal.imageset/PlayNormal.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PlayPurple.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PlayPurple.imageset/playPurple.svg
Labels: Ui

#41 22 add firebase forestore
  .swiftlint.yml
  MeditationAppUI.xcodeproj/project.pbxproj
  README.md
  scripts/pre-commit
Labels: Do Not Merge

#47 Enlaze de Pantallas, add ChooseTopicView, add HappyMorningView
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI/App/MeditationAppUIApp.swift
  MeditationAppUI/Presentation/ChooseTopic/ChooseTopicView.swift
  MeditationAppUI/Presentation/HappyMorning/HappyMorningView.swift
  MeditationAppUI/Presentation/Home/HomeView.swift
  MeditationAppUI/Presentation/Meditation/MeditationView.swift
  MeditationAppUI/Presentation/PlayMusic/PlayMusicView.swift
  MeditationAppUI/Presentation/Principal/Component/TextToolbarContent.swift
  MeditationAppUI/Presentation/Principal/PrincipalView.swift
  MeditationAppUI/Presentation/Profile/ProfileView.swift
  MeditationAppUI/Presentation/Reminderes/Component/ButtonDaysReminderes.swift
  MeditationAppUI/Presentation/Reminderes/ReminderesView.swift
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackgroundCard10.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackgroundCard3.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackgroundCard4.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackgroundCard5.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackgroundCard6.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackgroundCard7.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackgroundCard8.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Colores.xcassets/AccentBackgroundCard9.colorset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/BetterSleep.imageset/BetterSleep.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/BetterSleep.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/ChooseFondo.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/ChooseFondo.imageset/chooseTopicFond.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/ImprovePerformace.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/ImprovePerformace.imageset/improvePerformanee.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/IncraseHappiness.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/IncraseHappiness.imageset/IncraseHappiness.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PersonalGrowth.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/PersonalGrowth.imageset/PersonalGrowth.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Reduce.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/Reduce.imageset/Reduce.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/ReduceStress.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/ReduceStress.imageset/ReduceStr.svg
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/TimeMeditation.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/TimeMeditation.imageset/alarmMeditation.svg
Labels: enhancement, Ui

#59 Added dependency injection
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI/App/AppDelegate.swift
  MeditationAppUI/DI/Injector.swift
  MeditationAppUI/Presentation/Meditation/MeditationView.swift
  MeditationAppUI/Presentation/SignIn/SignInView.swift
  MeditationAppUI/Presentation/SignUp/SignUpView.swift
  Podfile
  Podfile.lock
Labels: enhancement

#58 Open camera in swiftui with permissions
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI.xcodeproj/project.pbxproj.orig
  MeditationAppUI/Info.plist
  MeditationAppUI/Presentation/Profile/Camera/AccessCameraView.swift
  MeditationAppUI/Presentation/Profile/Camera/CameraManager.swift
  MeditationAppUI/Presentation/Profile/Image/PHImagePickerView.swift
  MeditationAppUI/Presentation/Profile/ProfileView.swift
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/ProfileCamera.imageset/Contents.json
  MeditationAppUI/Resources/Assets/Imagenes.xcassets/ProfileCamera.imageset/profile_camera.png
Labels: enhancement, Ui

#61 Update HomeView, AddHomeViewModel, add HomeUiState, add HomeMeditatio…
  MeditationAppUI.xcodeproj/project.pbxproj
  MeditationAppUI/DI/Injector.swift
  MeditationAppUI/Domain/Modelo/HomeMeditation.swift
  MeditationAppUI/Presentation/Home/HomeUiState.swift
  MeditationAppUI/Presentation/Home/HomeView.swift
  MeditationAppUI/Presentation/Home/HomeViewModel.swift
  MeditationAppUI/Presentation/Meditation/MeditationView.swift
  MeditationAppUI/Presentation/Meditation/MeditationViewModel.swift
Labels: documentation, enhancement
